### ISSUE TITLE
Code snippets are not easy to read

### ISSUE THREAD

**Issue by RichardMcSorley** [walmartlabs/concord-website#1]
Tested in Firefox and Chrome
Lines seem to lose their formatting
```
- task: http in: method: GET url: "https://api.example.com:port/path/endpoint" response: string out: response
- if: ${response.success} then: - log: "Response received: ${response.content}"
```
https://concord.walmartlabs.com/docs/plugins/http.html

**Comment by ibodrov** [comment]
Here's how it looks for me (FF 64.0) 
![image](https://user-images.githubusercontent.com/826959/51804510-d4c50600-222f-11e9-82be-d304f26854c8.png)
The rest of the examples look fine too. @mosabua are you seeing any issues there?

**Comment by RichardMcSorley** [comment]
Looks the same in Chromium Version 71.0.3578.98 (Official Build) (64-bit) and Firefox 64.02 (64-bit)

Like this:
![screenshot from 2019-01-27 11-38-06](https://user-images.githubusercontent.com/6407008/51804587-8eb87400-2228-11e9-837f-9fac9694a89e.png)

Same on both my Linux Desktop and Macbook

**Comment by RichardMcSorley** [comment]
In the mean time a user can view the proper formatting by clicking the `Edit this page on GitHub` found on the top right hand corner of every page.

**Comment by mosabua** [comment]
We will do more testing but the code snippets work fine for me as well on Linux/Chrome. @aliloney will check it out more.

**Comment by mosabua** [comment]
We determined the most likely source of the problem as whitespace removal as part of performance optimization and are working with the relevant time to troubleshoot and disable. If you have walmart internal access .. please use the internal URL for now.

**Comment by mosabua** [comment]
This is now fixed.
