### ISSUE TITLE
Crypto plugin v2 encryption example is wrong

### ISSUE THREAD

**Issue by simbambili** [walmartlabs/concord-website#124]
In [Encrypting and Decrypting Values](https://concord.walmart.com/docs/plugins-v2/crypto.html#encrypting-and-decrypting-values) documentation section, the example given for encrypting strings is
```
- expr: ${crypto.encryptString('MyOrg', 'MyProject', 'my secret value')}
  out: encryptedValue
```
when it should be
```
- expr: ${crypto.encryptString('my secret value')}
  out: encryptedValue
```

**Comment by benbroadaway** [comment]
Thanks for reporting! Addressed in https://github.com/walmartlabs/concord-website/pull/125
